### ISSUE TITLE
Only for bugs

### ISSUE THREAD

**Issue by ndeeH** [ostreifel/duplicate-bug#3] opened 2018-01-30 12:59 UTC
Hi Otto,
does this extension only work for work item type "Bug".
We would love to use something like this for our own created work item type "ChangeRequest".
Thank you,
Andi

**Comment by ostreifel** [comment] 2018-01-30 17:14
It looks for duplicate of what ever is the current work item type. Bugs are the most common use case but the extension can be used with any wit.

**Closed as completed by ostreifel** 2018-01-30 17:14 UTC
